#!/usr/bin/env python3
import sys
import mongoengine as me
import datetime

from apiapp import models


def create_admin():
    print("create admin")

    user = models.User(
        email="admin@example.com",
        username="admin",
        title_name="นาย",
        first_name="admin",
        last_name="admin",
        status="active",
        roles=["user", "admin"],
    )

    user.password = user.set_password("p@ssw0rd")
    user.save()
    print("create admin success")


if __name__ == "__main__":
    if len(sys.argv) > 1:
        me.connect(db="kapkorndb", host=sys.argv[1])
    else:
        me.connect(db="kapkorndb")
    print("start create")
    create_admin()
    print("success")
